language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install: python setup.py install
script:
  - cd tests
  - python ../setup.py test
notifications:
  irc: "irc.freenode.org#quikpy"
  on_success: "never"
